export const comicTitle = document.querySelector('.comic-title')
export const comicImage = document.querySelector('.comic-image img')
export const comicDescription = document.querySelector('.comic-description')
export const notification = document.querySelector('.notification')

export const prevButton = document.querySelector('.prev-button')
export const nextButton = document.querySelector('.next-button')
export const randomButton = document.querySelector('.random-button-js')
export const toBeginButton = document.querySelector('.to-begin-button-js')
export const toEndButton = document.querySelector('.to-end-button-js')
